[package]
name = "fetcher"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
maycoon = { path = "../..", features = ["tokio-runner"] }
surf = "2.3.2"
serde = { version = "1", features = ["derive"] }
